### ISSUE TITLE
Don't delete root element

### ISSUE THREAD

**Issue by jbaum98** [alohaeditor/Aloha-Editor#1328] opened 2015-02-03 05:20 UTC
Currently, if Aloha is initialized on an empty div or if all of the content in a div is deleted, and backspace is pressed, the div itself is removed from the DOM. On Google Chrome.

**Comment by tanelkarp** [comment] 2015-02-04 16:43
Duplicate of #1265

**Closed** 2015-02-04 17:07 UTC

**Comment by petrosalema** [comment] 2015-02-09 14:18
Fixed! 0478451
